name: Release

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      dry_run:
        description: Dry run
        type: boolean
        default: false
      version_scheme:
        description: Scheme version
        type: choice
        options:
          - major
          - minor
          - patch
        default: minor
      release_notes:
        description: Release Notes
        type: boolean
        default: true

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: ${{ github.event.inputs.version_scheme }}
          tag_prefix: v
          use_github_release_notes: ${{ github.event.inputs.release_notes }}
          dry_run: ${{ github.event.inputs.dry_run }}

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.release.outputs.tag_name }}"
          echo "Got release version ${{ steps.release.outputs.version }}"
          echo "Upload release artifacts to ${{ steps.release.outputs.upload_url }}"
