name: tests ddev-kibana

on:
  pull_request:
  push:
    branches: [ main ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' #semantic version format

  schedule:
    - cron: '00 07 * * 5'

  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Debug with tmate set "debug_enabled"'
        required: false
        default: "false"

defaults:
  run:
    shell: bash

permissions:
  contents: write

env:
  GITHUB_REPOSITORY: janopl/ddev-kibana

jobs:
  tests:
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        ddev_version: [ stable ] # ddev_version: [stable, edge, HEAD, PR]
        os: [ubuntu-22.04] # os: ubuntu-20.04, ubuntu-22.04, macos-12, macos-11, ubuntu-latest, macos-latest, windows-2019, windows-2022, windows-latest
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
#    - uses: actions/checkout@v3
#      with:
#        submodules: 'true'

    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Environment setup
      run: |
        brew install jq

    - name: Download docker images
      run: |
        docker pull kibana:7.17.6 >/dev/null

    - uses: julienloizelet/ddev-add-on-test@v0.3.0
      with:
        ddev_version: ${{ matrix.ddev_version }}
        token: ${{ secrets.GITHUB_TOKEN }}
        debug_enabled: ${{ github.event.inputs.debug_enabled }}
        addon_repository: ${{ env.GITHUB_REPOSITORY }}



